version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - rt-network

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    restart: always
    networks:
      - rt-network
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer:/data/portainer

  web-app:
    build:
      context: ./
      dockerfile: DockerfileWebApp
    ports:
      - "4200:4200"
    restart: always
    networks:
      - rt-network
    volumes:
      - web-app:/data/web-app

  api:
    build:
      context: ./
      dockerfile: DockerfileApi
    ports:
      - "3000:3000"
    restart: always
    networks:
      - rt-network
    volumes:
      - api:/data/api

volumes:
    postgres:
    portainer:
    web-app:
    api:

networks:
  rt-network:
    driver: bridge          







